config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get 'orderlist', to: 'cabinet#view'
  
  resources :posts
  resources :services
  resources :prices
  
  resources :cabinet do
  	get :show_order
  	get :show
    get :refresh
    get :show_status
  end

  resources :contacts

  root "pages#mainpage"

  get '/about', to: 'pages#about'
  #get '/clients', to: 'pages#clients'
  get '/contactus', to: 'pages#contactus'
  post '/contactus', to: 'pages#contactus'
end

app/models/service.rb
class Service < ApplicationRecord
	belongs_to :user

	#Проверка на заполненость
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	
	def index
		@services = Service.all.order('created_at DESC')
	end

	def new
		if current_user.id == 1
			@service = current_user.services.build
		else
			redirect_to root_path
		end		
	end


	def create
		if current_user.id == 1
			@service = current_user.services.build(service_params)
		else
			redirect_to root_path
		end	
		
		if @service.save
			redirect_to @service
		else
			render 'new'	
		end	
	end

	def show
		@services = Service.all.order('created_at DESC')
		@service = Service.find(params[:id])
	end	


	def edit
		if current_user.id == 1
			@service = Service.find(params[:id])
		else
			redirect_to root_path
		end			
	end	


	def update
		@service = Service.find(params[:id])

		if @service.update(params[:service].permit(:title, :body, :imageurl))
			redirect_to @service
		else
			render 'edit'
		end	
	end	

	def destroy
		@service = Service.find(params[:id])
		@service.destroy

		redirect_to root_path
	end	

	private
		def service_params	
			params.require(:service).permit(:title, :body, :imageurl)
		end	
		
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<div class="col-md-12">
	<div class="row">
		<div class="create-edit-blog">
			<%= form_for @service do |f| %>
					<% if @service.errors.any? %>
						<div id="errors">
							<h2><%= pluralize(@service.errors.count, "error") %> prevented this service from saving</h2>
							<ul>
								<% @service.errors.full_messages.each do |msg| %>
									<li><%= msg %></li>
								<% end %>
							</ul>
						</div>
					<% end %>
					<div class="form_group">
						<%= f.label :Заголовок %><br>
						<%= f.text_field :title, class: "form-control" %>
					</div>
				<br>		
					<div class="form_group">
						<%= f.label :Текст %><br>
						<%= f.text_area :body, class: "blog-text-area form-control" %>
					</div>
				<br>
					<div class="form_group">
<<<<<<< HEAD
						<%= f.label :Зображення %><br>
=======
						<%= f.label :Изображение %><br>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
						<%= f.text_field :imageurl %>
					</div>
				<br>
					<div class="blog-edit text-center">
						<p><%= f.submit class: "btn btn-danger" %>
<<<<<<< HEAD
						<%= link_to 'Назад', edit_user_registration_path, class: "btn btn-back" %></p>
=======
						<%= link_to 'Назад', edit_user_registration_path, class: "btn btn-primary" %></p>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
					</div>
			<% end %>
		</div>
	</div>
</div>

app/views/services/edit.html.erb
<div class="container">
	<div class="row">
<<<<<<< HEAD
		<h1>Редагування</h1>
=======
		<h1>Редактирование</h1>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333

		<%= render 'services/form' %>
	</div>
	
</div>

app/views/services/index.html.erb
<div class="container">
	<a class="anchor" id="services"></a>
	<div class="row">
		<% @services.each do |service| %>
			<div class="wpb_wrapper">
			<div class="wdc-service">
			<div class="post-item col-md-4 col-sm-6 col-xs-12 software">
				<div class="service-container style-1">
					<div class="service-icon"><span><i class="<%= service.imageurl %>"></i></span></div>
						<div class="service-content">
							<h4><%= link_to service.title, service %></h4>
							<div class="boxs">
								<div>
								<p><%= service.body %></p>
								<script src="jquery.dotdotdot.min.js"></script>
								</div>
							</div>
						</div>
<<<<<<< HEAD
						<%= link_to "Детальніше", service, class: "wdc-button style-1 size-medium" %>
=======
						<%= link_to "Подробнее", service, class: "wdc-button style-1 size-medium" %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
					<div class="clearfix"></div>
				</div>

			</div>
		</div>
	</div>
		<% end %>
	</div>
	<a class="anchor" id="aboutus"></a>
	<div class="row">
			<div class="title title-pages text-center" id="stop">
<<<<<<< HEAD
				<h3>Комп'ютерна швидка допомога "Мегабайт" надає наступні послуги:</h3>
=======
				<h3>Компьютерная скорая помощь "Мегабайт" предоставляет следующие услуги:</h3>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
			</div>
			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<h4>Сервис по ремонту компьютеров и ноутбуков установке и наладке ПО.</h4>
					<p>При наличии необходимых комплектующих ремонт компьютеров выполняется в день обращения. 
					При вызове мастера по ремонту компьютеров на дом или в офис, выезд специалистов бесплатный!
					Мы делаем не только физический ремонт компьютеров, ремонт ноутбуков, но и установку программного обеспечения, настройку системы на оптимальное быстродействие, защитим Ваш компьютер или ноутбук от вирусов.
					Произведем модернизацию компьютера или ноутбука, соберем компьютер на заказ.</p>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<h4>Заправка картриджей, ремонт оргтехники.</h4>
					<p>Одним из видов нашей деятельности является заправка картриджей, ремонт оргтехники,
					а также продажа новых оригинальных и совместимых картриджей для струйных и лазерных принтеров.
					Заправкой картриджей и ремонтом ксероксов и принтеров занимаются многие компании, 
					но далеко не все предоставляют своим клиентам качественный сервис.
					Самое важное отличие нашей компании от других заключается в комплексном подходе к оргтехнике клиента.</p>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<h4>Одно из направлений деятельности нашего сервисного центра - ремонт TFT и CRT мониторов.</h4>
					<p>Мы осуществляем ремонт мониторов всех марок и практически всех моделей: LG, Samsung, Sony,
					ViewSonic, Daewoo, CTX, Hyundai, Panasonic, Nokia, Falcon, ADI, NEC, Mag, Mitsubishi,
					HP, Acer, Bridge и др. Наши цены на ремонт мониторов не зависят от производителя или марки монитора, они зависят от количества вышедших из строя блоков. 
					Сложный электромеханический ремонт производится только в стационарном сервисе.</p>
				</div>
				<div class="col-xs-12 col-sm-6 col-md-6">
					<h4>Мы предоставляем услуги по подключению и установке оборудования "СПУТНИКОВОГО ИНТЕРНЕТА".</h4>
					<p>Запросный канал пользователя осуществляется через любое доступное наземное подключение 
					(DialUP, DSL, выделенная линия, радиоканал, GPRS и т.п.) поступает на сервер спутникового оператора.
					Сервер получает необходимые данные из интернет, отправляет их на спутник, пользователь посредством спутниковой антенны и DVB-приемника получает запрошенные данные.
					Наземное подключение должно быть постоянным, т.к. обмен данными происходит непрерывно.</p>
				</div>
			</div>

			<div class="row">
				<div class="col-xs-12 col-sm-6 col-md-6">
					<h4>Спутниковое телевидение.</h4>
					<p>Вам надоело, что любимые фильмы прерываются рекламой на 20 минут?
					Вам надоела дряблая картинка на Вашем экране?
					Вам хочется смотреть больше каналов?
					Вас не устраивает набор программ?
					Тогда Ваш выбор - Спутниковое телевидение.
					Множество каналов, отсутствие рекламы, огромный выбор фильмов, спортивных, детских и новостных передач скрасят Ваш досуг.
					Спутниковое телевидение - выбор современного человека.</p>
				</div>
			</div>
	</div>
	<div class="enpty_space"></div>
	<div class="row">
			<div class="col-xs-12 col-sm-12 col-md-12 text-center">
<<<<<<< HEAD
				<p>Для більш детального ознайомлення з послугами, ознайомтесь з 
				<%= link_to "прайсом", prices_path %>
				або
				<%= link_to "подзвоніть нашому менеджеру", contacts_path %>.</p>
=======
				<p>Для более детального ознакомления с услугой ознакомтесь с 
				<%= link_to "прайсом", prices_path %>
				или
				<%= link_to "позвоните нашему менеджеру", contacts_path %>.</p>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
			</div>
	</div>
	<div class="enpty_space"></div>


<a class="anchor" id="clients"></a>
		
		<div class="row">
			<div class="title-pages text-center">
<<<<<<< HEAD
				<h3>З нами працюють</h3>
=======
				<h3>С нами работают</h3>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
			</div>
		</div>
		<div class="row">
			<div class="col-xs-12 col-sm-6 col-md-6">
<<<<<<< HEAD
				<h4>Наші партнери</h4>
=======
				<h4>Наши партнеры</h4>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
				<p>Компании и организации, которые помогают нам осуществлять качественный сервис для Вас</p>
				<ul class="company_help">
					<li><%= link_to "АО 'Техника'", "http://www.texnika.com.ua" %></li>
					<li><%= link_to "Группа компаний 'В.М.'", "http://www.vm.ua/"%></li>
					<li><%= link_to "Компания 1С", "http://1c.ua/"%></li>
				</ul>
			</div>
			
			<div class="col-xs-12 col-sm-6 col-md-6">
<<<<<<< HEAD
				<h4>Наші клієнти</h4>
=======
				<h4>Наши клиенты</h4>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
				<strong>Бюджетные организации</strong>
				<p>Более 140 организаций Славянска и Славянского района сотрудничают с нами на протяжении многих лет.</p>

				<strong>Предприятия разных форм собственности</strong>
				<p>Более 1000 компаний пользуются нашей техподдержкой в своих офисах.</p>

				<strong>Частные лица</strong>
				<p>В базе данных предприятия числится свыше 10000 адресов.</p>

<<<<<<< HEAD
				<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Детальніше</button>
=======
				<button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">Подробнее</button>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333

				<!-- Modal -->
				<div id="myModal" class="modal fade" role="dialog">
				  <div class="modal-dialog">

				    <!-- Modal content-->
				    <div class="modal-content">
				      <div class="modal-header">
				        <button type="button" class="close" data-dismiss="modal">&times;</button>
				        <h4 class="modal-title">Наши клиенты</h4>
				      </div>
				      <div class="modal-body">
				        <ul class="modal_ul">
				        	<li>Славянская рекламно информационная "Газета объявлений"</li>
				        	<li>Газета в формате журнала "Экран Славянска"</li>
				        	<li>Агенство недвижимости "Акцент"</li>
				        	<li>"СЛАВКЕРАМОГНЕУПОР"</li>
				        	<li>Профидент</li>
				        	<li>"Господар"</li>
				        	<li>Центр "Колесо"</li>
				        	<li>"Монитор"</li>
				        	<li>"МТС" на САТУ</li>
				        	<li>АВК "Недвижимость"</li>
				        	<li>Автодор</li>
				        	<li>Автосалон "Еврокласс"</li>
				        	<li>Агенство недвижимости "Акцент"</li>
				        	<li>Андреевский поселковый совет</li>
				        	<li>Андреевский сельский совет</li>
				        	<li>АО "Индекс банк"</li>
				        	<li>Ателье "Славяночка"</li>
				        	<li>Аудиторская фирма "ТОР"</li>
				        	<li>Бар "ULTRA"</li>
				        	<li>Благотворительный фонд "Хесед Мориа"</li>
				        	<li>Больница №2</li>
				        	<li>БрокбизнессБанк</li>
				        	<li>Былбасовская аудитория</li>
				        	<li>Былбасовский поселковый совет</li>
				        	<li>Велес</li>
				        	<li>ВОЗ "РДА"</li>
				        	<li>ВКПП "Термо-златополь"</li>
				        	<li>Военкомат</li>
				        	<li>ГАИ</li>
				        	<li>гостиница "Украина"</li>
				        	<li>гостиница "Европа"</li>
				        	<li>ГП УкрНИИметаллургмаш</li>
				        	<li>ДЗ "ВЛ ст Словянск"</li>
				        	<li>ДизайнСтудияПлюс</li>
				        	<li>Диалог Либерти</li>
				        	<li>Дмитровская школа</li>
				        	<li>ДОЛ СТ "Солнечный"</li>
				        	<li>И многие другие...</li>

				        </ul>
				      </div>
				      <div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				      </div>
				    </div>

				  </div>
				</div>


			</div>
		</div>
</div>		
<div class="enpty_space"></div>

<script>
$(function(){
  $('.boxs').dotdotdot();
});
</script>

<script>
	var myHash = location.hash; //получаем значение хеша
	//location.hash = ''; //очищаем хеш
	if(myHash[1] != undefined){ //проверяем, есть ли в хеше какое-то значение
    $('html, body').animate({scrollTop: $(myHash).offset().top}, 1500); //скроллим за полсекунды
};
</script>

app/views/services/new.html.erb
<div class="container">
	<div class="row">
		<div class="text-center">
			<h3>Новый сервис</h3>
		</div>
		<div class="blog-edit-form">				
			<%= render 'services/form' %>
		</div>
	</div>
</div>

app/views/services/show.html.erb
<div class="blog-content">
	<div class="container">
		<div class="row">
			<main id="main-wrapper" class="col-md-9 col-md-push-3">
				<div class="post-content">
					<div class="vc_row wpb_row vc_row-fluid wpb_padding">
						<div class="wpb_column vc_column_container vc_col-sm-8">
							<div class="wpb_wrapper">
								<div class="wdc-heading style-1 text-left">
									<h3 class="box-title"><%= @service.title %></h3>
								</div>
								<div class="wpb_text_column wpb_content_element ">
									<p><%= @service.body %></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</main>
			<aside id="sidebar-wrapper" class="col-md-3 col-md-pull-9">
				<section id="wdc-services-wgt-1" class="widget wdc-services-wgt">
					<% @services.each do |service| %>
					<ul>
						<li><%= link_to service.title, service %></li>
					</ul>
					<% end %>
				</section>
			</aside>
		</div>	
		<div class="blog-edit text-center">
				<% if user_signed_in? %>
        			<% if current_user.id == 1 %>
<<<<<<< HEAD
					<p><%= link_to 'Редагувати', edit_service_path(@service), class: "btn btn-sm btn-danger" %>
					<%= link_to 'Видалити', service_path(@service), method: :delete, data: { confirm: 'Вы уверены?'},class: "btn btn-sm btn-danger" %>
=======
					<p><%= link_to 'Редактировать', edit_service_path(@service), class: "btn btn-sm btn-danger" %>
					<%= link_to 'Удалить', service_path(@service), method: :delete, data: { confirm: 'Вы уверены?'},class: "btn btn-sm btn-danger" %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
					<%= link_to 'Назад', root_path, class: "btn btn-sm btn-primary" %>	
					</p>
					<% end %>
				<% end %>	
		</div>
	</div>
</div>
<div class="enpty_space"></div>
<div class="enpty_space"></div>