config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get 'orderlist', to: 'cabinet#view'
  
  resources :posts
  resources :services
  resources :prices
  
  resources :cabinet do
  	get :show_order
  	get :show
    get :refresh
    get :show_status
  end

  resources :contacts

  root "pages#mainpage"

  get '/about', to: 'pages#about'
  #get '/clients', to: 'pages#clients'
  get '/contactus', to: 'pages#contactus'
  post '/contactus', to: 'pages#contactus'
end

app/controllers/cabinet_controller.rb
class CabinetController < ApplicationController
  
  require "orderlist"

  def view
  	
 	if user_signed_in?
 		#byebug
		@list = OrderList.getlist(current_user.id, params[:from_date], params[:to_date])
	else
		redirect_to new_user_session_path
	end
	
  end

  def show_order
    #byebug
    @details_u = OrderList.getdetails_usl(params[:cabinet_id])
    @details_t = OrderList.getdetails_tov(params[:cabinet_id])
  	#byebug
  	respond_to do |format|
  		format.js
  	end
  end

  def show
    respond_to do |format|
      format.js
    end
  end
  
  def refresh
    #byebug
    view
    respond_to do |format|
      format.js
    end
  end

def show_status
    @status = OrderList.getstatus(params[:order_number])
    #byebug
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/cabinet_helper.rb
module CabinetHelper
end

app/views/cabinet/_all.html.erb
	<div class="row">
		<div class="col-xs-7 col-sm-1 text-center table-margin" > <strong>Дата</strong> </div>
<<<<<<< HEAD
		<div class="col-xs-7 col-sm-1 text-center table-margin" > <strong>Замовлення</strong> </div>
		<div class="col-xs-7 col-sm-2 text-center table-margin" > <strong>Статус</strong> </div>
		<div class="col-xs-7 col-sm-3 text-center table-margin" > <strong>Менеджер</strong> </div>
		<div class="col-xs-7 col-sm-3 text-center table-margin" > <strong>Майстер</strong> </div>
		<div class="col-xs-7 col-sm-1 text-center table-margin" > <strong>Сума,грн.</strong> </div>
=======
		<div class="col-xs-7 col-sm-1 text-center table-margin" > <strong>№ Заказа</strong> </div>
		<div class="col-xs-7 col-sm-2 text-center table-margin" > <strong>Статус</strong> </div>
		<div class="col-xs-7 col-sm-3 text-center table-margin" > <strong>Менеджер</strong> </div>
		<div class="col-xs-7 col-sm-3 text-center table-margin" > <strong>Мастер</strong> </div>
		<div class="col-xs-7 col-sm-1 text-center table-margin" > <strong>Сумма,грн.</strong> </div>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
		<!--div class="col-xs-7 col-sm-1" > Акт </div-->
	</div>

	<% @list.each do |row| %>

		<div class="row" style="<%= cycle("background: #e0f8f8;","background: #ffffff;") %>">
<<<<<<< HEAD
			<div class="col-xs-7 col-sm-1 table-margin"> <%= row["_Date_Time"].strftime("%d.%m.%Y") %> </div>
			<div class="col-xs-7 col-sm-1 table-margin"> <%= row["_Number"]%> <br> <%= link_to "Показати", cabinet_show_order_path(row["_IDRRef"]), id: "link"+row["_IDRRef"], remote: true %> 
				<%= link_to "Приховати", cabinet_show_path(row["_IDRRef"]), id: "l"+row["_IDRRef"], hidden: true, remote: true %></div>
=======
			<div class="col-xs-7 col-sm-1 table-margin"> <%= row["_Date_Time"].strftime("%Y.%m.%d") %> </div>
			<div class="col-xs-7 col-sm-1 table-margin"> <%= row["_Number"]%> <br> <%= link_to "Показать", cabinet_show_order_path(row["_IDRRef"]), id: "link"+row["_IDRRef"], remote: true %> 
				<%= link_to "Скрыть", cabinet_show_path(row["_IDRRef"]), id: "l"+row["_IDRRef"], hidden: true, remote: true %></div>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
			<div class="col-xs-7 col-sm-2 table-margin"> <%= OrderList.description_status(row["Status"]) %>  </div>
			<div class="col-xs-7 col-sm-3 table-margin"> <%= row["Manager"] %> </div>
			<div class="col-xs-7 col-sm-3 table-margin"> <%= row["Master"] %> </div>
			<div class="col-xs-7 col-sm-1 table-margin"> <%= row["Summa"] %> </div>
			<!--div class="col-xs-7 col-sm-1"> <a href="assets/Akt.pdf">Акт в PDF</a> </div-->
		</div>

		<div id="<%=row["_IDRRef"]%>" style="display: none">

		</div>

	<% end %>
<div class="enpty_space"></div>	

app/views/cabinet/_details.html.erb
<%# byebug %>

<% if @details_u.first %>

	<div class="row" >
		<div class="col-xs-6 col-sm-1">  </div>
		<div class="col-xs-6 col-sm-7" style="padding: 0px 140px; background-color: gainsboro">
<<<<<<< HEAD
			Послуги
=======
			Услуги
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
		</div>
	</div>

	<% @details_u.each do |row_det|%>
				<%# byebug %>
				<div class="row">
					<div class="col-xs-6 col-sm-1">  </div>
					<div class="col-xs-6 col-sm-5"><%= row_det["Descr"] %> </div>
					<div class="col-xs-6 col-sm-1"><%= row_det["Kol"] %> шт.</div>
					<div class="col-xs-6 col-sm-3"><%= row_det["Summa"] %> грн.</div>
					
				</div>
	<% end %>

<% end %> <!-- there are service records -->


<%# byebug %>
<% if @details_t.first %>

	<div class="row"> 
		<div class="col-xs-6 col-sm-1">  </div>
		<div class="col-xs-6 col-sm-7" style="padding: 0px 140px; background-color: gainsboro">
<<<<<<< HEAD
			Товари
=======
			Товары
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
		</div>
		
	</div>

	<% @details_t.each do |row_det|%>
				<%# byebug %>
				<div class="row">
					<div class="col-xs-6 col-sm-1">  </div>
					<div class="col-xs-6 col-sm-5"><%= row_det["Descr"] %> </div>
					<div class="col-xs-6 col-sm-1"><%= row_det["Kol"] %> шт.</div>
					<div class="col-xs-6 col-sm-3"><%= row_det["Summa"] %> грн.</div>
					
				</div>
	<% end %>

<% end %> <!-- there are products entries -->

<br>

app/views/cabinet/refresh.js.erb
if ($('#<%=params[:cabinet_id]%> div').length == 0) { $('#all_row').html("<%= j render("all") %>"); }

app/views/cabinet/show.js.erb
$('#<%=params[:cabinet_id]%>').toggle()

if ($('#<%=params[:cabinet_id]%>').is(':visible')) {
    // виден
<<<<<<< HEAD
$('#<%="l"+params[:cabinet_id]%>').html('Приховати')
=======
$('#<%="l"+params[:cabinet_id]%>').html('Скрыть')
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
}

else {
    // не виден
<<<<<<< HEAD
$('#<%="l"+params[:cabinet_id]%>').html('Показати')
=======
$('#<%="l"+params[:cabinet_id]%>').html('Показать')
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
}

app/views/cabinet/show_order.js.erb
//$('#<%=params[:cabinet_id]%>').toggle()
$('#<%=params[:cabinet_id]%>').show()

if ($('#<%=params[:cabinet_id]%> div').length == 0) { $('#<%=params[:cabinet_id]%>').html("<%= j render("details") %>"); }

if ($('#<%=params[:cabinet_id]%>').is(':visible')) {
    // виден
$('#<%="link"+params[:cabinet_id]%>').hide()
$('#<%="l"+params[:cabinet_id]%>').show()
}

app/views/cabinet/show_status.js.erb
//$('#status').toggle()
$('#status').html('<%=@status%>')

app/views/cabinet/view.html.erb
<div class="container">

<<<<<<< HEAD
<h4>Замовлення за період: </h4>
=======
<h4>Заказы c: </h4>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
<div class="row">
	
	    <%= form_tag cabinet_refresh_path('all'), method: "get", remote: true do %>
	    <div class="col-xs-3 col-sm-2">
		    <%= date_field_tag :from_date, Date.today - 1.month %>
		 </div>
		 <div class="col-xs-3 col-sm-2">
		    <%= date_field_tag :to_date, Date.today %>
		 </div>
		 <div class="col-xs-3 col-sm-2">
<<<<<<< HEAD
		    <%= submit_tag "Показати" %>
=======
		    <%= submit_tag "Показать" %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
		</div>
	    <% end %>
	</div>

<br>

<%# byebug %> 

<div id="all_row">

<%= render("all") %>

</div>
</div><!--/container-->