config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get 'orderlist', to: 'cabinet#view'
  
  resources :posts
  resources :services
  resources :prices
  
  resources :cabinet do
  	get :show_order
  	get :show
    get :refresh
    get :show_status
  end

  resources :contacts

  root "pages#mainpage"

  get '/about', to: 'pages#about'
  #get '/clients', to: 'pages#clients'
  get '/contactus', to: 'pages#contactus'
  post '/contactus', to: 'pages#contactus'
end

app/models/price.rb
class Price < ApplicationRecord
  has_many :pricelists, inverse_of: :price, :dependent => :destroy

  accepts_nested_attributes_for :pricelists, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true
end

app/controllers/prices_controller.rb
class PricesController < ApplicationController
	before_action :find_price, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@prices = Price.all.order('created_at DESC')
	end
	
	def new
		if current_user.id == 1
			@price = Price.new
		else
			redirect_to root_path
		end		
	end

	def create
		if current_user.id == 1
			@price = Price.new(price_params)
		else
			redirect_to root_path
		end	

		if @price.save
			redirect_to @price, notice: "Успешно создана группа прайслиста"
		else 
			render 'new'
		end	
	end	

	def show
	end

	def edit
		if current_user.id == 1
			@price = Price.find(params[:id])
		else
			redirect_to root_path
		end		
	end
	
	def update
		if @price.update(price_params)
			redirect_to @price
		else
			render 'edit'
		end		
	end

	def destroy
		@price.destroy
		redirect_to prices_path, notice: "Группа прайс-листа успешно удалена"
	end	

private
	def price_params
		params.require(:price).permit(:title, pricelists_attributes: [:id, :name, :value, :_destroy])
	end	

	def find_price
		@price = Price.find(params[:id])
	end	
end

app/helpers/prices_helper.rb
module PricesHelper
end

app/views/prices/_form.html.erb
<div class="col-md-12">	
	<div class="row">
		<div class="create-edit-price">
			<%= form_for @price, html: {multipart: true} do |f| %>
				<% if @price.errors.any? %>
					<div id="errors">
						<h2><%= pluralize(@price.errors.count, "error") %> prevented this price from saving</h2>
						<ul>
							<% @price.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</div>
				<% end %>
	
	
				<div class="form_group">
<<<<<<< HEAD
						<%= f.text_field :title, placeholder: "Послуга", class: "form-control" %>
				</div>
				
			<div class="title-pages text-center">
				<h3>Послуги і ціни</h3>
=======
						<%= f.text_field :title, placeholder: "Заголовок услуг", class: "form-control" %>
				</div>
				
			<div class="title-pages text-center">
				<h3>Услуги и цены</h3>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
			</div>

			 <div id='pricelists'>
			    <%= f.fields_for :pricelists do |pricelist| %>
			      <%= render 'pricelist_fields', :f => pricelist %>
			    <% end %>
			    
			    <div class='links'>
<<<<<<< HEAD
			      <%= link_to_add_association 'Добавити послугу', f, :pricelists, class: "btn btn-primary" %>
=======
			      <%= link_to_add_association 'Добавить услугу', f, :pricelists, class: "btn btn-primary" %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
			    </div>
			</div>
			
			<% if user_signed_in? %>
        	<% if current_user.id == 1 %>	
				<div class="price-buttons text-center">
					<p><%= f.submit class: "btn btn-danger" %>
<<<<<<< HEAD
					<%= link_to 'Назад', edit_user_registration_path, class: "btn btn-back" %></p>
=======
					<%= link_to 'Назад', edit_user_registration_path, class: "btn btn-primary" %></p>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
				</div>
			<% end %>	
			<% end %>
			<% end %>
		</div>	
	</div>	
</div>			

app/views/prices/_pricelist_fields.html.erb
 <div class='nested-fields'>
    <div class="price_form">
	    <div class="field">
<<<<<<< HEAD
	      <%= f.text_field :name, placeholder: "Послуга" %>
	    </div>
	    <div class="field">
	      <%= f.text_field :value, placeholder: "Ціна (грн., шт.)" %>
	    </div>
	    <%= link_to_remove_association "Видалити", f %>
=======
	      <%= f.text_field :name, placeholder: "Услуга" %>
	    </div>
	    <div class="field">
	      <%= f.text_field :value, placeholder: "Цена (грн., шт.)" %>
	    </div>
	    <%= link_to_remove_association "Удалить", f %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
    </div>
 </div>

app/views/prices/edit.html.erb
<div class="container">
	<div class="row">
		<div class="title-pages text-center">
<<<<<<< HEAD
			<h3>Редагування групи прайс-листа</h3>
=======
			<h3>Редактирование группы прайс-листа</h3>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
		</div>
		<%= render 'prices/form' %>
	</div>
</div>

app/views/prices/index.html.erb
<a class="anchor" id="uslugi"></a>
<div class="price_index">
	<div class="container">
		<div class="row">
			<div class="title-pages text-center">
				<h3>Наш прайс-лист</h3>
			</div>
		</div>

		<div class="row">
			<div class="prices">
				<ul class="price_ul">
					<% @prices.each do |price| %>
						<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
							<%= link_to price do %>	
							<div class="title-pages text-center">
								<h3><%= price.title %></h3>
								<% end %>	
							</div>
							
							<div class="price_blog">
								<% price.pricelists.each do |pricelist| %>
									<li class="price_list"> 
										<div class="pricelist_name">
											<%= pricelist.name %> 
										</div>
										<div class="pricelist_value">
											<%= pricelist.value %> 
										</div>
									</li>
								<% end %>
							</div>
							<div class="price_link">
<<<<<<< HEAD
								<%= link_to "Детальніше...", price %>
=======
								<%= link_to "Подробнее...", price %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
							</div>
						</div>		
					<% end %>
				</ul>
			</div>
		</div>
		
	</div>
</div>			

<script>
	var myHash = location.hash; //получаем значение хеша
	//location.hash = ''; //очищаем хеш
	if(myHash[1] != undefined){ //проверяем, есть ли в хеше какое-то значение
    $('html, body').animate({scrollTop: $(myHash).offset().top}, 150); //скроллим за полсекунды
};
</script>

app/views/prices/new.html.erb
<div class="container">
	<div class="row">
		<div class="title-pages text-center">
<<<<<<< HEAD
			<h3>Створення групи прайс-листа</h3>
=======
			<h3>Создание группы прайс-листа</h3>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
		</div>
		<%= render 'prices/form' %>
	</div>
	
</div>

app/views/prices/show.html.erb
<div class="price-content">
	<div class="container">
		<div class="row">
			<div class="title-pages text-center">
				<h3><%= @price.title %></h3>
			</div>
		<div class="row">
			<div class="col-md-12">
				<div id="pricelists">
					<ul>
						<% @price.pricelists.each do |pricelist| %>
							<li> 
								<div class="price_show_name">
									<%= pricelist.name %>
								</div> 
								<div class="price_show_value">
									<%= pricelist.value %> 
								</div>
							</li>
						<% end %>
					</ul>	
				</div>
			</div>
		</div>				
			<div class="blog-edit text-center">
				<% if user_signed_in? %>
        			<% if current_user.id == 1 %>
<<<<<<< HEAD
					<p><%= link_to 'Редагувати', edit_price_path(@price), class: "btn btn-sm btn-danger" %>
					<%= link_to 'Видалити', price_path(@price), method: :delete, data: { confirm: 'Вы уверены?'},class: "btn btn-sm btn-danger" %>
=======
					<p><%= link_to 'Редактировать', edit_price_path(@price), class: "btn btn-sm btn-danger" %>
					<%= link_to 'Удалить', price_path(@price), method: :delete, data: { confirm: 'Вы уверены?'},class: "btn btn-sm btn-danger" %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
					<%= link_to 'Назад', prices_path, class: "btn btn-sm btn-primary" %>	
					</p>
					<% end %>
				<% end %>
			</div>
		</div>
	</div>
</div>