config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  
  get 'orderlist', to: 'cabinet#view'
  
  resources :posts
  resources :services
  resources :prices
  
  resources :cabinet do
  	get :show_order
  	get :show
    get :refresh
    get :show_status
  end

  resources :contacts

  root "pages#mainpage"

  get '/about', to: 'pages#about'
  #get '/clients', to: 'pages#clients'
  get '/contactus', to: 'pages#contactus'
  post '/contactus', to: 'pages#contactus'
end

app/views/layouts/_footer.html.erb
<footer id="myFooter">
        <div class="container">
            <div class="row">
                <div class="col-sm-3 myCols">
                    <h5>Get started</h5>
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#">Sign up</a></li>
                        <li><a href="#">Downloads</a></li>
                    </ul>
                </div>
                <div class="col-sm-3 myCols">
                    <h5>About us</h5>
                    <ul>
                        <li><a href="#">Company Information</a></li>
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">Reviews</a></li>
                    </ul>
                </div>
                <div class="col-sm-3 myCols">
                    <h5>Support</h5>
                    <ul>
                        <li><a href="#">FAQ</a></li>
                        <li><a href="#">Help desk</a></li>
                        <li><a href="#">Forums</a></li>
                    </ul>
                </div>
                <div class="col-sm-3 myCols">
                    <h5>Legal</h5>
                    <ul>
                        <li><a href="#">Terms of Service</a></li>
                        <li><a href="#">Terms of Use</a></li>
                        <li><a href="#">Privacy Policy</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="social-networks">
            <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
            <a href="#" class="facebook"><i class="fa fa-facebook-official"></i></a>
            <a href="#" class="google"><i class="fa fa-google-plus"></i></a>
        </div>
        <div class="footer-copyright">
            <p>© 2018 Copyright Text </p>
        </div>
    </footer>
                 

app/views/layouts/_header.html.erb
<header class="main-header">
  <section class="header-wrapper navgiation-wrapper">
     <nav class="navbar navbar-default navbar-fixed-top">
      <div class="repair-header-top">
      <div class="container">
        <div class="opacity-block"></div>
        <div class="row">
          <div class="col-md-3 col-sm-12 repair-col-logo">
            <div class="megabyte-logo">
              <%= link_to root_path do %>
                <%= image_tag "logo.jpg" %>
              <% end %>
            </div>
          </div>
          <div class="col-md-7 hidden-sm hidden-xs">
            <div class="row">
              <div class="col-md-4">
              </div>
              <div class="col-md-4">
                <div class="repair-icon-box">
                  <div class="icon-container">   
                      <span class="glyphicon glyphicon-phone"></span>
                  </div>
                  <div class="text">
<<<<<<< HEAD
                    <span class="head-heading"><font color="white">Подзвоніть нам</font></span>
=======
                    <span class="head-heading"><font color="white">Позвоните нам</font></span>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
                    <span class="head-content">+380971234567</span>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="repair-icon-box">
                  <div class="icon-container">   
                      <span class="glyphicon glyphicon-time"></span>
                  </div>
                  <div class="text">
<<<<<<< HEAD
                    <span class="head-heading"><font color="white">Робочий час</font></span>
                    <span class="head-content">Пн.-Нд. 9.00 - 18.00</span>
=======
                    <span class="head-heading"><font color="white">Рабочее время</font></span>
                    <span class="head-content">Пн.-Вс. 9.00 - 18.00</span>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
                  </div>
                </div>
              </div>

            </div>
          </div>
          <div class="col-md-2 hidden-sm hidden-xs">
            <div class="btn-quote">
<<<<<<< HEAD
              <%= link_to "Замовити послугу", contactus_path + "#contactus", class: "btn-request_quote" %>
=======
              <%= link_to "Заказать услугу", contactus_path + "#contactus", class: "btn-request_quote" %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
            </div>
          </div>
        </div>
      </div>
    </div>

   
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar-main">
          
          <ul class= "nav navbar-nav">
            <li><%#= link_to "О нас", about_path, class: "active" %></li>
<<<<<<< HEAD
            <li><%= link_to "Сервіс", services_path, class: "active" %></li>
            <li><%= link_to "Блог", posts_path, class: "active" %></li>
            <li><%#= link_to "Клиенты", clients_path, class: "active" %></li>
            <li><%= link_to "Прайс-лист", prices_path, class: "active" %></li>
            <li><%= link_to "Контакти", contacts_path, class: "active" %></li>
            <!-- Кнопка, открывающая модальное окно -->
            <li><a href="#statdoc" class="active" data-toggle="modal">Статус замовлення</a></li>
=======
            <li><%= link_to "Сервис", services_path, class: "active" %></li>
            <li><%= link_to "Блог", posts_path, class: "active" %></li>
            <li><%#= link_to "Клиенты", clients_path, class: "active" %></li>
            <li><%= link_to "Прайс", prices_path, class: "active" %></li>
            <li><%= link_to "Контакты", contacts_path, class: "active" %></li>
            <!-- Кнопка, открывающая модальное окно -->
            <li><a href="#statdoc" class="active" data-toggle="modal">Статус заказа</a></li>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
          </ul>

          <% if user_signed_in? %>
            <ul class= "nav navbar-nav navbar-right">

              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Аккаунт
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
<<<<<<< HEAD
                  <li><%= link_to "Список замовлень", orderlist_path %></li>
                  <li><%= link_to "Змінити аккаунт", edit_user_registration_path + "#adminpage"%></li>
=======
                  <li><%= link_to "Список заказов", orderlist_path %></li>
                  <li><%= link_to "Изменить аккаунт", edit_user_registration_path + "#adminpage"%></li>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
                </ul>
             </li>

      
<<<<<<< HEAD
              <li> <%= link_to "Вийти", destroy_user_session_path, method: :delete %> </li>
            </ul>
          <% else %>
            <ul class= "nav navbar-nav navbar-right">
              <li> <%= link_to "Увійти", new_user_session_path %> </li>
              <li> <%= link_to "Реєстрація", new_user_registration_path %> </li>
=======
              <li> <%= link_to "Выйти", destroy_user_session_path, method: :delete %> </li>
            </ul>
          <% else %>
            <ul class= "nav navbar-nav navbar-right">
              <li> <%= link_to "Войти", new_user_session_path %> </li>
              <li> <%= link_to "Регистрация", new_user_registration_path %> </li>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
            </ul>
          <% end %> 
          
        </div> 

      </div>
    </nav>
  </section>
</header>

<div id="myCarousel" class="carousel fade-carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner">
    <div class="item active">
      <%= image_tag "carusel1.jpg", class: "img-responsive" %>
       <div class="hero">
          <hgroup>
<<<<<<< HEAD
            <h1>Ми надійні</h1>        
            <h3>Відремонтуйтесь у нас з гарантією</h3>
          </hgroup>
          <a href="#statdoc" class="active btn btn-info btn-lg" data-toggle="modal">Статус замовлення</a>
          <%= link_to "Замовити послугу", contactus_path + "#contactus", class: "btn btn-info btn-lg" %>
=======
            <h1>We are creative</h1>        
            <h3>Get start your next awesome project</h3>
          </hgroup>
          <a href="#statdoc" class="active btn btn-info btn-lg" data-toggle="modal">Статус заказа</a>
          <%= link_to "Заказать услугу", contactus_path + "#contactus", class: "btn btn-info btn-lg" %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
        </div>
    </div>

    <div class="item">
      <%= image_tag "carusel2.jpg", class: "img-responsive" %>
         <div class="hero">
          <hgroup>
<<<<<<< HEAD
            <h1>Креативні ми</h1>        
            <h3>Продіагностуйте своє обладнання</h3>
          </hgroup>
          <a href="#statdoc" class="active btn btn-info btn-lg" data-toggle="modal">Статус замовлення</a>
          <%= link_to "Замовити послугу", contactus_path + "#contactus", class: "btn btn-info btn-lg" %>
=======
            <h1>We are creative</h1>        
            <h3>Get start your next awesome project</h3>
          </hgroup>
          <a href="#statdoc" class="active btn btn-info btn-lg" data-toggle="modal">Статус заказа</a>
          <%= link_to "Заказать услугу", contactus_path + "#contactus", class: "btn btn-info btn-lg" %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
        </div>  
    </div>

    <div class="item">
      <%= image_tag "carusel3.jpg", class: "img-responsive" %>
        <div class="hero">
          <hgroup>
<<<<<<< HEAD
            <h1>Ми креативні</h1>        
            <h3>Будьте впевнені в ремонті своєї техніки</h3>
          </hgroup>
          <a href="#statdoc" class="active btn btn-info btn-lg" data-toggle="modal">Статус замовлення</a>
          <%= link_to "Замовити послугу", contactus_path + "#contactus", class: "btn btn-info btn-lg" %>
=======
            <h1>We are creative</h1>        
            <h3>Get start your next awesome project</h3>
          </hgroup>
          <a href="#statdoc" class="active btn btn-info btn-lg" data-toggle="modal">Статус заказа</a>
          <%= link_to "Заказать услугу", contactus_path + "#contactus", class: "btn btn-info btn-lg" %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
        </div>  
    </div>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<script>
 $(window).scroll(function(){
    $(".opacity-block").each(function () {
      var scrolled;
      window.onscroll = function() {
      scrolled = window.pageYOffset || document.documentElement.scrollTop;
      if(scrolled > 100){
        $(".opacity-block").addClass('stick_bottom'); 
    }
    if(100 > scrolled){
        $(".opacity-block").removeClass('stick_bottom'); 
        $(".opacity-block").addClass('stick_top');       
    }

}
    });
});
</script>

app/views/layouts/_header_page.html.erb
<header class="main-header">
  <section class="header-wrapper navgiation-wrapper">
     
      <div class="repair-header-top">
      <div class="container">
        <div class="row">
          <div class="col-md-3 col-sm-12 repair-col-logo">
            <div class="megabyte-logo">
              <%= link_to root_path do %>
                <%= image_tag "logo.jpg" %>
              <% end %>
            </div>
          </div>
          <div class="col-md-7 hidden-sm hidden-xs">
            <div class="row">
              <div class="col-md-4">
              </div>
              <div class="col-md-4">
                <div class="repair-icon-box">
                  <div class="icon-container">   
                      <span class="glyphicon glyphicon-phone"></span>
                  </div>
                  <div class="text">
                    <span class="head-heading">Позвоните нам</span>
                    <span class="head-content">+380971234567</span>
                  </div>
                </div>
              </div>
              <div class="col-md-4">
                <div class="repair-icon-box">
                  <div class="icon-container">   
                      <span class="glyphicon glyphicon-time"></span>
                  </div>
                  <div class="text">
                    <span class="head-heading">Рабочее время</span>
                    <span class="head-content">Пн.-Вс. 9.00 - 18.00</span>
                  </div>
                </div>
              </div>

            </div>
          </div>
          <div class="col-md-2 hidden-sm hidden-xs">
            <div class="btn-quote">
              <%= link_to "Заказать услугу", prices_path, class: "btn-request_quote" %>
            </div>
          </div>
        </div>
      </div>
    </div>

   <nav class="navbar navbar-inverse">
      <div class="container"> 
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-main">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar-main">
          
          <ul class= "nav navbar-nav">
            <li><%#= link_to "О нас", about_path, class: "active" %></li>
            <li><%= link_to "Сервис", services_path, class: "active" %></li>
            <li><%= link_to "Клиенты", clients_path, class: "active" %></li>
            <li><%= link_to "Прайс", prices_path, class: "active" %></li>
            <li><%= link_to "Контакты", contacts_path, class: "active" %></li>
          </ul>

          <% if user_signed_in? %>
            <ul class= "nav navbar-nav navbar-right">

              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">Аккаунт
                  <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Список заказов", orderlist_path %></li>
                  <li><%= link_to "Изменить аккаунт", edit_user_registration_path %></li>
                </ul>
             </li>

      
              <li> <%= link_to "Выйти", destroy_user_session_path, method: :delete %> </li>
            </ul>
          <% else %>
            <ul class= "nav navbar-nav navbar-right">
              <li> <%= link_to "Войти", new_user_session_path %> </li>
              <li> <%= link_to "Регистрация", new_user_registration_path %> </li>
            </ul>
          <% end %> 
          
        </div> 

      </div>
    </nav>
  </section>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Megabyte</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- HTML-код модального окна "проверка заказа"-->
<div id="statdoc" class="modal fade">
  <div class="modal-dialog modal-sm">
    <div class="modal-content">
      <!-- Основное содержимое модального окна -->
      <div class="modal-body">
<<<<<<< HEAD
        Інформація про статус замовлення
=======
        Информация о статусе заказа
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
      </div>
      <!-- Футер модального окна -->
      <div class="modal-footer">

        <%= form_tag(cabinet_show_status_path('query-status'), method: "get", remote: true) do %>
<<<<<<< HEAD
          <%= text_field_tag :order_number, nil, maxlength: 10, placeholder: "Введіть № замовлення", size: 26 %>
          <br><br>
          <div id="status" style="color: #2196F3; font-size: 1.3em; text-align: center;"></div>
          <br>
          <%= submit_tag 'Показати', class: "btn btn-primary" %>
          <%= submit_tag 'Відміна', class: "btn btn-default", data: {dismiss: "modal"} %>
=======
          <%= text_field_tag :order_number, nil, maxlength: 10, placeholder: "Введите № заказа", size: 26 %>
          <br><br>
          <div id="status" style="color: #2196F3; font-size: 1.3em; text-align: center;"></div>
          <br>
          <%= submit_tag 'Показать', class: "btn btn-primary" %>
          <%= submit_tag 'Отмена', class: "btn btn-default", data: {dismiss: "modal"} %>
>>>>>>> f5b642ed63968df69d7c6ff0aad10b516b291333
        <% end %>

      </div>
      <!-- -->
    </div>
  </div>
</div>

    <%= render('layouts/header') %><!--if @mainpage %>-->
    <!--<%#= render('layouts/header_page') if @mainpage == nil%>-->
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>